# Generated by Django 3.2.8 on 2022-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('imagem', models.ImageField(null=True, upload_to='imagens', verbose_name='Imagem')),
                ('descricao', models.TextField(null=True, verbose_name='descricao')),
            ],
        ),
    ]
